name:               tractor
version:            0.4.8
github:             ak1211/tractor
license:            AGPL-3
author:             Akihiro Yamamoto
maintainer:         ak1211@mail.ak1211.com
copyright:          (c) 2016 Akihiro Yamamoto.

extra-source-files:
- README.md
#- ChangeLog.md

# Metadata used when publishing your package
synopsis:           tractor is an Assets observation application.
category:           Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/ak1211/tractor#readme>

dependencies:
- base >=4.7 && <5
- bytestring
- conduit
- directory
- elm-export
- gitrev
- http-conduit
- http-types
- monad-logger
- mtl
- resourcet
- safe-exceptions
- servant-elm
- stm
- text
- time
- utf8-string

library:
  source-dirs: src
  ghc-options: -Wall
  dependencies:
  - aeson
  - attoparsec
  - case-insensitive
  - cassava
  - conduit-extra
  - connection
  - containers
  - html-conduit
  - http-media
  - iconv
  - lucid
  - mwc-random
  - network-uri
  - optparse-simple
  - persistent
  - persistent-mysql
  - persistent-template
  - safe
  - servant
  - servant-cassava
  - servant-docs
  - servant-lucid
  - servant-server
  - tagsoup
  - template-haskell
  - transformers
  - vector
  - wai
  - warp
  - xml-conduit
  - yaml
  - zeromq4-haskell

executables:
  tractor:
    main:               Main.hs
    source-dirs:        app
    ghc-options:
    - -rtsopts
    - -threaded
    - -Wall
    - -with-rtsopts=-N
    dependencies:
    - async
    - monad-logger-syslog
    - optparse-applicative
    - persistent-mysql
    - tractor

tests:
  tractor-test:
    main:               Spec.hs
    source-dirs:        test
    ghc-options:
    - -rtsopts
    - -threaded
    dependencies:
    - connection
    - hspec
    - QuickCheck
    - tractor
  code-gen:
    main:               Main.hs
    source-dirs:        code-generator
    ghc-options:
    - -rtsopts
    - -threaded
    - -Wall
    dependencies:
    - servant-docs
    - shelly
    - tractor

